apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend   # 对应 deployment 里的占位符
  newName: frontend-will-be-replaced
  newTag: latest