apiVersion: v1
kind: Service
metadata:
  name: stock-web-svc
spec:
  type: NodePort # 方便你部署完直接通过节点 IP 访问
  selector:
    app: stock-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081 # 部署后可通过 http://<K8s节点IP>:30080 访问扫雷游戏